#!/bin/bash

# Execute the script by sourcing it as . ./setup because ./setup will 
# trigger a subprocess to source the dot files and it's benefits will 
# not be available in the terminal where the bash script is executed.

# Description: Link dot-config-files to home directory

# Prevent running as a separate process
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "Error: Script must be sourced, not executed directly."
    echo "Run: source ${0}"
    exit 1
fi

link_file() {
    local src="$1"
    local dest="$2"

    if [[ -f "$src" ]]; then
        ln -sf "$src" "$dest"
        echo "Linked: $dest -> $src"
    else
        echo "Warning: Source file $src does not exist. Skipping."
    fi
}

dotfiles=(
    "$HOME/dot-config-files/bashrc/bashrc"
    "$HOME/dot-config-files/bashrc/bash_aliases"
    "$HOME/dot-config-files/vimrc/vimrc"
    "$HOME/dot-config-files/tmux/tmux.conf"
    "$HOME/dot-config-files/git/gitconfig"
    "$HOME/dot-config-files/commands/commands.txt"
)
# Form the needed arguments and call the function link_file
for item in "${dotfiles[@]}"; do
    filename="${item##*/}"
    
    if [[ "$filename" == "commands.txt" ]]; then
        link_file "$item" "$HOME/$filename"
    else
        link_file "$item" "$HOME/.$filename"
    fi
done

echo "Dotfiles linked!"

# Source .tmux.conf and .bashrc
if command -v tmux &>/dev/null && tmux info &>/dev/null; then
    tmux source-file "$HOME/.tmux.conf"
    echo "Tmux config reloaded."
fi

if [[ -f "$HOME/.bashrc" ]]; then
    source "$HOME/.bashrc"
    echo "Bash configuration reloaded."
fi
