#!/bin/bash

# Execute the script by sourcing it as . ./setup because ./setup will 
# trigger a subprocess to source the dot files and it's benefits will 
# not be available in the terminal where the bash script is executed.

# Description: Link dot-config-files to home directory

ln -sf ~/dot-config-files/bashrc/bashrc ~/.bashrc
ln -sf ~/dot-config-files/bashrc/bash_aliases ~/.bash_aliases
ln -sf ~/dot-config-files/vimrc/vimrc ~/.vimrc
ln -sf ~/dot-config-files/tmux/tmux.conf ~/.tmux.conf
ln -sf ~/dot-config-files/git/gitconfig ~/.gitconfig
ln -sf ~/dot-config-files/commands/commands.txt ~/commands.txt

echo "Dotfiles linked!"

# Source .tmux.conf and .bashrc
if \tls &>/dev/null; then
    \tmux source-file ~/.tmux.conf
fi

source ~/.bashrc

echo "Files sourced"
